on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: npm i
      - run: npx eslint .
      - run: npx jest
      - run: echo "üçè This job's status is ${{ job.status }}."
      - name: Run test & publish code coverage
        # uses: paambaati/codeclimate-action@v2.6.0
        # Add Code Climate secret key
        # env:
        #   CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        # with:
        #   coverageCommand: make test-coverage
        #   coverageLocations: ${{github.workplace}}/coverage/clover.xml:clover
        #   debug: true

        - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v3.0.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true